### PR TITLE
Basic block splitting

### LINKED ISSUE #5: Global Values
Global values are not currently recorded in the stack map. This means an `llvm.experimental.patchpoint` call inserted before an instruction such as `printf` might not record the correct state. This is because `printf` uses a format string, which is a global value. 

For example, consider the following scenario: in the optimized version, the global value is loaded into a register after the call to the `patchpoint` intrinsic happens (so its value is never recorded), while in the unoptimized version, the global variable is loaded before the `stackmap` call.

### PR DESCRIPTION
**Pull request by gabi-250**
I think it would be best to merge #21 first.

To fix #5, I had to split the basic blocks around `stackmap` calls (this seemed to prevent loads from being moved around). 

I realized late optimizations were removing some of the `br` instructions generated by the splitting. This branch fixes the problem by introducing a separate pass that splits the basic blocks. This pass runs later than all other passes, so its effects won't be optimized away.

### CODE REVIEW

**Comment by vext01** [comment]
Before I look at the code, did you try using an empty volatile asm block as a compiler barrier? This is a trick I've seen used recently.

**Comment by gabi-250** [comment]
@vext01 Hah, I tried that yesterday, but for some reason I decided to create this new pass. I tried it again just now to justify my decision to implement all this, and it seems like two empty `asm` blocks are sufficient. I'll get rid of the useless functionality and ping you when this is ready for review.

**Comment by gabi-250** [comment]
@vext01 This should be ready for review now.

**Comment by vext01** [comment]
Oh, great! It worked! Reviewing shortly.

**Comment by vext01** [comment]
LGTM. Squash?

**Comment by gabi-250** [comment]
@vext01 Done.

**Pull request merged**
